name: Catalog Processor

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [stock_update]

jobs:
  process-catalog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install system deps (Chromium & Chromedriver)
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          which chromium-browser
          chromium-browser --version
          which chromedriver
          chromedriver --version

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy selenium openpyxl requests
      
      - name: Run catalog process
        env:
          CHROME_BIN: /usr/bin/chromium-browser
          CHROMEDRIVER_PATH: /usr/bin/chromedriver
          STOCK_URL: ${{ github.event.client_payload.stock_url }}
        run: |
          python scripts/process_catalog.py

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
      
      - name: Configure rclone
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf

      - name: Upload to Google Drive
        run: |
          rclone copy "productos_filtrados_$(date +'%Y-%m-%d').xlsx" gdrive:1B-QForJBzGdCp7scDZbTonXx1unBIS7P --progress