name: Test catalog with Selenium

on:
  workflow_dispatch: {} # ejecución manual

jobs:
  test-catalog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install system deps (Chromium & Chromedriver)
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          which chromium-browser
          chromium-browser --version
          which chromedriver
          chromedriver --version

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl selenium

      - name: Run catalog script
        env:
          CHROME_BIN: /usr/bin/chromium-browser
          CHROMEDRIVER_PATH: /usr/bin/chromedriver
        run: python scripts/process_catalog.py

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: productos_filtrados
          path: productos_filtrados_*.xlsx
