name: Test catalog

on:
  workflow_dispatch: {} # ejecución manual

jobs:
  test-catalog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl

      - name: Run catalog script
        run: python scripts/process_catalog.py

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: productos_filtrados
          path: output/productos_filtrados.xlsx
