name: Catalog Processor

on:
  repository_dispatch:
    types: [stock_update]  # Disparado desde Power Automate

jobs:
  process-catalog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install system deps (Chromium & Chromedriver)
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          which chromium-browser
          chromium-browser --version
          which chromedriver
          chromedriver --version

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy selenium openpyxl

      - name: Save stock data from Power Automate
        run: |
          echo '${{ toJson(github.event.client_payload.value) }}' > stock_data.json
          echo "Stock data guardado correctamente"

      - name: Run catalog process
        env:
          CHROME_BIN: /usr/bin/chromium-browser
        run: python scripts/process_catalog.py
